-- Order System Supabase schema
-- Run this file in the Supabase SQL Editor.
-- The policies below are intentionally open because this frontend does not use Supabase Auth.
-- Add authentication-based policies before using this database in production.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) > 0)
);

create table if not exists public.menuitems (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) > 0),
  price numeric(12, 2) not null check (price >= 0),
  type text not null default 'food' check (type in ('food', 'drink'))
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  buyer_id bigint not null references public.users(id),
  order_date timestamptz not null default now(),
  total_amount numeric(12, 2) not null check (total_amount >= 0)
);

create table if not exists public.orderdetails (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  user_id bigint not null references public.users(id),
  item_id bigint not null references public.menuitems(id),
  quantity integer not null default 1 check (quantity > 0),
  price_at_time numeric(12, 4) not null check (price_at_time >= 0)
);

create table if not exists public.debt_payments (
  id bigint generated by default as identity primary key,
  from_user_id bigint not null references public.users(id),
  to_user_id bigint not null references public.users(id),
  amount numeric(12, 2) not null check (amount > 0),
  paid_at timestamptz not null default now(),
  check (from_user_id <> to_user_id)
);

create table if not exists public.social_posts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  content text not null check (length(trim(content)) > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.social_posts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.social_posts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  content text not null check (length(trim(content)) > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.member_photos (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  file_path text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.vote_sessions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  closed_order_id bigint references public.orders(id) on delete set null
);

create table if not exists public.drink_votes (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.vote_sessions(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  item_id bigint not null references public.menuitems(id),
  quantity integer not null default 1 check (quantity > 0),
  order_id bigint references public.orders(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists orders_buyer_id_idx on public.orders (buyer_id);
create index if not exists orders_order_date_idx on public.orders (order_date desc);
create index if not exists orderdetails_order_id_idx on public.orderdetails (order_id);
create index if not exists orderdetails_user_id_idx on public.orderdetails (user_id);
create index if not exists orderdetails_item_id_idx on public.orderdetails (item_id);
create index if not exists debt_payments_from_to_idx on public.debt_payments (from_user_id, to_user_id);
create index if not exists debt_payments_paid_at_idx on public.debt_payments (paid_at desc);
create index if not exists social_posts_created_at_idx on public.social_posts (created_at desc);
create index if not exists post_comments_post_id_idx on public.post_comments (post_id);
create index if not exists member_photos_user_id_idx on public.member_photos (user_id);
create index if not exists drink_votes_session_id_idx on public.drink_votes (session_id);

-- Enable RLS while keeping the current unauthenticated frontend functional.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users',
    'menuitems',
    'orders',
    'orderdetails',
    'debt_payments',
    'social_posts',
    'post_likes',
    'post_comments',
    'member_photos',
    'vote_sessions',
    'drink_votes'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists public_full_access on public.%I', table_name);
    execute format(
      'create policy public_full_access on public.%I for all to anon, authenticated using (true) with check (true)',
      table_name
    );
  end loop;
end $$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
